[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aiod_utils"
version = "0.0.1"
description = "Utilities for AI OnDemand"
readme = "README.md"
authors = [
    {name = "Cameron Shand"}
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]
keywords = ["image analysis", "segmentation"]
dependencies = [
    "bioio>=3.2.0",
    "bioio-imageio>=1.1.0",
    "bioio-ome-zarr>=2",
    "bioio-tifffile>=1.2.0",
    "tifffile",
    "numcodecs",
    "zarr>=3",
    "numpy>=1.26,<2.0",
    "opencv-python",
    "scikit-image>0.20",
    "pyyaml",
    "pandas<2.3.0"
]

[project.optional-dependencies]
testing = ["pytest"]
bioformats = ["bioio-bioformats"]
